const honeyKeywords = [
  "মধু",
  "খাটি মধু",
  "খাঁটি মধু",
  "মধু চেনার উপায়",
  "দুধ ও মধু",
  "মধু খাওয়ার নিয়ম",
  "মধু ও লেবু",
  "সুগার মধু",
  "আসল মধু চেনার উপায়",
  "মধু খেলে কি উপকারিতা",
  "মধু খাওয়ার উপকারিতা",
  "বিশুদ্ধ মধু",
  "organic মধু",
  "মৌমাছির মধু",
  "মধু খাওয়ার উপকারিতা কি",
  "মধু খেলে কি হয়",
  "সুন্দরবন মধু",
  "খাটি মধু ডট কম",
  "মধু চিনার উপায়",
  "গাছের মধু নাকি",
  "খাঁটি মধু ডটকম",
  "দুধের সাথে মধু",
  "প্রাকৃতিক মধু",
  "কালোজিরা ও মধু",
  "মধু মাখলে কি হয়",
  "খাঁটি মধু কোথায় পাওয়া যায়",
  "মধু খেলে কি হয় ?",
  "সুন্দরবনের মধু",
];

const mustardFlowerHoneyKeywords = [
  "সরিষা ফুলের মধু",
  "ফুলের মধু",
  "সরিষা ফুলের মধু চেনার উপায়",
  "সরিষা ফুলের মধু চেনার উপায়",
  "#সরিষা ফুলের মধু",
  "সরিষা ফুলের মধু সংগ্রহ",
  "সরিষার ফুলের মধু",
  "সরিষা ফুলের খাঁটি মধু",
  "সরিষা ফুলের মধু চাষ পদ্ধতি",
];

const mixedFlowerHoneyKeywords = [
  "মিক্স ফুলের মধু মধু",
  "লিচু ফুলের মধু",
  "কালোজিরা ফুলের মধু",
  "খাঁটি মধু",
  "সুন্দরবনের প্রাকৃতিক চাক ভাঙ্গা মিক্স ফুলের মধু",
  "বরই ফুলের মধু",
  "গরান ফুলের মধু",
  "সরিষা ফুলের মধু",
  "খলিশা ফুলের মধু",
  "ধনিয়া ফুলের মধু",
  "বাইন কেওড়া ফুলের মধু",
  "খলিশা ফুলের চাকের মধু",
  "খলিশা ফুলের চাক ভাঙা মধু",
  "কোন ফুলের মধু সবচেয়ে বেশি উপকারী",
  "মধু বিক্রেতা আলামিন",
  "সুন্দরবনের মধু",
  "ত্বক ও চুলের সমস্যায় মধু",
  "মধু মাখলে কি হয়",
  "দুধের সাথে মধু",
  "মিকক্স ফুড দাম কত",
  "খাঁটি মধু পরীক্ষা",
  "মধু পরীক্ষা করার নিয়ম",
  "সেরা মধু",
  "পিউর মধু",
];

const aphrodisiacKeywords = [
  "হালূয়া",
  "সেক্স বাড়ানোর প্রাকৃতিক হালুয়া",
  "যৌন শক্তি বৃদ্ধির প্রাকৃতিক উপায়",
  "যৌনশক্তি বাড়ানোর প্রাকৃতিক উপায়",
  "দ্রুত বীর্যপাতের প্রাকৃতিক সমাধান",
  "মহিলাদের সেক্স বাড়ানোর উপায়",
  "যৌন ক্ষমতা বাড়ানোর পদ্ধতি",
  "সেক্স পাওয়ার বাড়ানোর ওষুধ",
  "সেক্স পাওয়ার বাড়ানোর উপায়",
  "যৌন ক্ষমতা বাড়ানোর পদ্ধতি ঔষধ",
  "যৌনশক্তি বাড়ানোর মন্ত্র",
  "যৌন ক্ষমতা বাড়ানোর পদ্ধতি",
  "যৌন শক্তি বাড়ানোর উপায়",
  "যৌনশক্তি বাড়ানোর ঘরোয়া রেমেডি",
  "যৌন ক্ষমতা বাড়ানোর আমল",
  "যৌন ক্ষমতা বাড়ানোর খাবার",
  "যৌন ক্ষমতা বাড়ানোর ঔষধ",
];

const herbalMedicineKeywords = [
  "হারবাল ওষুধ",
  "হারবাল",
  "হারবাল ঔষধ",
  "হারবাল ওষুধ",
  "হারবার ওষুধ",
  "হারবাল ওষুধ খেলে কি হয়",
  "হারবাল ওষুধ কি বেশি নিরাপ",
  "হারবাল ওষুধে বিষক্রিয়া",
  "বিষাক্ত রং দিয়ে হারবাল ওষুধ তৈরি",
  "কলিকাতা হারবাল",
  "হারবাল চিকিৎসা",
  "হারবাল ওষুধের নামে কি খাচ্ছেন?",
  "হারবাল শিল্প",
  "মডার্ন হারবাল",
  "মর্ডান হারবাল",
  "হারবাল ঔষধ শিল্প",
  "হারবাল ফেসিয়াল",
  "হারবাল ঔষদের নামে",
  "হারবাল থেকে মুক্তি",
  "দেশী হারবাল চিকিৎসা",
  "কোরিয়ান হারবাল ঔষধ",
  "ডায়াবেটিস এবং হারবাল",
  "হারবাল খেলে মৃত্যু হয়",
  "হারবাল ও আয়ুর্বেদিক চিকিৎসা",
];

const herbalRemedyKeywords = [
  "ভেষজ হারবাল রেমিডি",
  "হারবাল তেল",
  "হারবাল তেল রেসিপি",
  "ঘরে তৈরি হারবাল তেল",
  "হারবাল হেয়ার অয়েল রেসিপি",
  "চুলের যত্নে ম্যাজিক হারবাল তেল",
  "ভেষজ চা",
  "ভেষজ হালুয়া",
  "হারবাল#",
  "হারবাল জুস",
  "রেমিডি জুস ( হার্ট ব্লক জুস)",
  "হারবাল চিকিৎসা",
  "ন্যাচারাল হুম রেমিডি ফর হেয়ার#",
  "হারবাল হেয়ার অয়েল",
  "হারবাল শ্যাম্পু #",
  "ভেষজ",
  "চুলের যত্নে ঘরোয়া রেমিডি",
  "ম্যাজিক হারবাল তেল ঘরে তৈরি",
  "কিডনি রোগে ভেষজ",
  "নতুন চুল গজাতে ম্যাজিক হারবাল তেল",
  "ভেষজ তেল",
  "বীর্য্য গাঢ়া করার হারবাল মেডিসিন",
  "ভেষজ ঔষধ",
  "খুশকি দূর করবে হারবাল তেল",
];

const alkoshiKeywords = [
  "আলকুশি",
  "আলকুশি বীজের উপকারিতা",
  "আলকুশি বীজ",
  "আলকুশি বীজ শোধন পদ্ধতি",
  "আলকুশি বীজ খাওয়ার নিয়ম",
  "আলকুশি গাছ",
  "আলকুশি বীজ চূর্ণ",
  "আলকুশি কি",
];

const panchbhutaKeywords = [
  "পঞ্চভুত",
  "পঞ্চভুত খাওয়ার উপকারিতা",
  "পঞ্চভুত খাওয়ার সঠিক নিয়ম",
  "পঞ্চভূত",
  "পঞ্চভূত কি কি",
  "পঞ্চভুত কিভাবে তৈরি হয়",
  "পঞ্চভূত অর্থ",
  "পঞ্চভুত খেলে কি হয়",
  "পঞ্চভুত খাওয়ার নিয়ম",
  "পঞ্চভুত কি",
  "পঞ্চভুত কিভাবে খাবেন",
];

const ashwagandhaKeywords = [
  "অশ্বগন্ধা",
  "অশ্বগন্ধার উপকারিতা",
  "অশ্বগন্ধা পাউডার",
  "অশ্বগন্ধার উপকারিতা কি",
  "অশ্বগন্ধার উপকারিতা ও অপকারিতা",
];

const veeryamaniKeywords = [
  "বীর্যমনি",
  "বীর্যমনি ফল",
  "বীর্যমনি ফলের উপকারিতা",
  "বীর্যমনি ফল কি",
  "বীর্যমনী গাছ",
  "বীর্যমূল",
  "বীর্যমনি ফল খেলে কি হয়",
  "বীর্যমনি ফল উপকারিতা",
  "বীর্যমনি ফলের গুনাগুন",
];

const shimulKeywords = [
  "শিমুল",
  "শিমুল মুলের গুডা",
  "শিমুল মূলের উপকারিতা",
  "শিমুল গাছের মূলের উপকারিতা",
  "শিমুল মূল",
  "শিমুল মূলের উপকারিতা",
  "শিমুলের মূলের উপকারিতা",
  "শিমুল গাছ",
];

const banglishKeywords = [
  // Modhu
  "honey",
  "pure honey",
  "original honey",
  "sundarban honey bd",
  "natural honey",
  "organic honey",
  "imported honey brands in bd",
  "pure honey in bangladesh",
  "honey in bangladesh",
  "best honey in dhaka",
  "honey price in bangladesh",
  "honey collection in bd",

  // Halua
  "halwa recipe",
  "halwa",
  "suji ka halwa",
  "gajar ka halwa",
  "halua recipe",
  "sooji halwa",
  "carrot halwa",
  "gajar ka halwa recipe",
  "sooji ka halwa recipe",
  "sooji ka halwa",
  "bangladeshi halua recipe",
  "buter daler halua",
  "carrot halwa recipe",
  "daler halua",
  "buter halua",
  "gajor halua",
  "suji halwa",
  "gajar halwa recipe",
  "rava halwa",
  "halua recipe bangla",
];

export const allkeywords = [
  ...aphrodisiacKeywords,

  ...herbalMedicineKeywords,
  ...herbalRemedyKeywords,
  ...honeyKeywords,

  ...mixedFlowerHoneyKeywords,
  ...mustardFlowerHoneyKeywords,
  ...alkoshiKeywords,
  ...panchbhutaKeywords,
  ...ashwagandhaKeywords,
  ...veeryamaniKeywords,
  ...shimulKeywords,
  ...banglishKeywords,
];

export const descriptionShop =
  "Welcome to prakrito.com, your premier destination for an unparalleled shopping experience! At prakrito.com, we pride ourselves on offering a vast array of high-quality products to meet all your needs and desires. Whether you're searching for the latest fashion trends, cutting-edge electronics, home essentials, or unique gifts, we've got you covered.\n\nWith a user-friendly interface and intuitive navigation, prakrito.com makes it easy for you to browse through our extensive collection of items. From clothing and accessories to gadgets and appliances, our diverse range ensures that there's something for everyone.\n\nAt prakrito.com, we are committed to providing our customers with top-notch service and exceptional value. Our team works tirelessly to source the best products from trusted brands and suppliers, ensuring that you receive nothing but the finest quality merchandise.\n\nShopping with us is not just about making a purchase—it's about embarking on a journey of discovery and delight. With new arrivals regularly added to our inventory, you'll always find something exciting and inspiring at prakrito.com.\n\nExperience the convenience of online shopping like never before with prakrito.com. Shop with confidence, knowing that your satisfaction is our top priority. Join us today and elevate your shopping experience to new heights!";
