name: Deploy to Production

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production' && (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true))
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd prakrito/
            git pull -u origin production
            pnpm run build
            pm2 restart 7
